STATUS_WILL_DEQUEUE = 'WILL DEQUEUE'
STATUS_DEQUEUED = 'DEQUEUED'
STATUS_RUNNING = 'RUNNING'
STATUS_SUCCESS = 'SUCCESS'
STATUS_ERROR = 'ERROR'

PATH_STDIN = "input/stdin"
PATH_ARGS = "input/args"
PATH_INPUT_FILES = "input/files"
PATH_STATUS = "status"
PATH_PROGRESS = "progress"

ENV_KEY_ADBI_BASE_DIR = 'ADBI_BASE_DIR'
ENV_KEY_SQS_NAME = 'ADBI_SQS_NAME'
ENV_KEY_MAX_WORKER = 'ADBI_MAX_WORKER'
