STATUS_SUCCESS = 'SUCCESS'
STATUS_ERROR = 'ERROR'
PATH_STDIN = "input/stdin"
PATH_ARGS = "input/args"
PATH_INPUT_FILES = "input/files"
PATH_STATUS = "status"
PATH_PROGRESS = "progress"

ENV_KEY_ADBI_BASE_DIR = 'ADBI_BASE_DIR'
ENV_KEY_SQS_NAME = 'ADBI_SQS_NAME'
